apiVersion: v1

# Tipo de recurso
kind: Service

metadata:
  # Nombre del Service que expone el cliente para mirar
  name: servicio-visualizacion

spec:
  # Selector que indica a qué pods dirige el tráfico este service. coincide con el del deployment
  selector:
    app: cliente-visualizacion

  # Puertos expuestos por el Service
  ports:
    - port: 8081
      targetPort: 8081

      # Puerto del nodo por el cual se accede desde el navegador
      nodePort: 30081

  # Tipo de Service
  # NodePort permite acceso desde fuera del clúster
  type: NodePort

# PRUEBA
# kubectl apply -f 08-service-cliente.yaml
# kubectl get svc servicio-visualizacion
# Minikube:
# minikube service servicio-visualizacion
